out(i    , j    , k    ) = c[ 0] * in(i    , j    , k    )
                         + c[ 1] * in(i - 5, j    , k    )
                         + c[ 2] * in(i - 4, j    , k    )
                         + c[ 3] * in(i - 3, j    , k    )
                         + c[ 4] * in(i - 2, j    , k    )
                         + c[ 5] * in(i - 1, j    , k    )
                         + c[ 6] * in(i + 1, j    , k    )
                         + c[ 7] * in(i + 2, j    , k    )
                         + c[ 8] * in(i + 3, j    , k    )
                         + c[ 9] * in(i + 4, j    , k    )
                         + c[10] * in(i + 5, j    , k    )
                         + c[11] * in(i    , j - 5, k    )
                         + c[12] * in(i    , j - 4, k    )
                         + c[13] * in(i    , j - 3, k    )
                         + c[14] * in(i    , j - 2, k    )
                         + c[15] * in(i    , j - 1, k    )
                         + c[16] * in(i    , j + 1, k    )
                         + c[17] * in(i    , j + 2, k    )
                         + c[18] * in(i    , j + 3, k    )
                         + c[19] * in(i    , j + 4, k    )
                         + c[20] * in(i    , j + 5, k    )
                         + c[21] * in(i    , j    , k - 5)
                         + c[22] * in(i    , j    , k - 4)
                         + c[23] * in(i    , j    , k - 3)
                         + c[24] * in(i    , j    , k - 2)
                         + c[25] * in(i    , j    , k - 1)
                         + c[26] * in(i    , j    , k + 1)
                         + c[27] * in(i    , j    , k + 2)
                         + c[28] * in(i    , j    , k + 3)
                         + c[29] * in(i    , j    , k + 4)
                         + c[30] * in(i    , j    , k + 5);
