out(i    , j    , k    ) = c[ 0] * in(i    , j    , k    )
                         + c[ 1] * in(i - 2, j    , k    )
                         + c[ 2] * in(i - 1, j    , k    )
                         + c[ 3] * in(i + 1, j    , k    )
                         + c[ 4] * in(i + 2, j    , k    )
                         + c[ 5] * in(i    , j - 2, k    )
                         + c[ 6] * in(i    , j - 1, k    )
                         + c[ 7] * in(i    , j + 1, k    )
                         + c[ 8] * in(i    , j + 2, k    )
                         + c[ 9] * in(i    , j    , k - 2)
                         + c[10] * in(i    , j    , k - 1)
                         + c[11] * in(i    , j    , k + 1)
                         + c[12] * in(i    , j    , k + 2);
