out(i    , j    ) = c[ 0] * in(i    , j    )
                  + c[ 1] * in(i - 7, j    )
                  + c[ 2] * in(i - 6, j    )
                  + c[ 3] * in(i - 5, j    )
                  + c[ 4] * in(i - 4, j    )
                  + c[ 5] * in(i - 3, j    )
                  + c[ 6] * in(i - 2, j    )
                  + c[ 7] * in(i - 1, j    )
                  + c[ 8] * in(i + 1, j    )
                  + c[ 9] * in(i + 2, j    )
                  + c[10] * in(i + 3, j    )
                  + c[11] * in(i + 4, j    )
                  + c[12] * in(i + 5, j    )
                  + c[13] * in(i + 6, j    )
                  + c[14] * in(i + 7, j    )
                  + c[15] * in(i    , j - 7)
                  + c[16] * in(i    , j - 6)
                  + c[17] * in(i    , j - 5)
                  + c[18] * in(i    , j - 4)
                  + c[19] * in(i    , j - 3)
                  + c[20] * in(i    , j - 2)
                  + c[21] * in(i    , j - 1)
                  + c[22] * in(i    , j + 1)
                  + c[23] * in(i    , j + 2)
                  + c[24] * in(i    , j + 3)
                  + c[25] * in(i    , j + 4)
                  + c[26] * in(i    , j + 5)
                  + c[27] * in(i    , j + 6)
                  + c[28] * in(i    , j + 7);
