out(i    , j    ) = c[ 0] * in(i - 2, j - 2)
                  + c[ 1] * in(i - 1, j - 2)
                  + c[ 2] * in(i    , j - 2)
                  + c[ 3] * in(i + 1, j - 2)
                  + c[ 4] * in(i + 2, j - 2)
                  + c[ 5] * in(i - 2, j - 1)
                  + c[ 6] * in(i - 1, j - 1)
                  + c[ 7] * in(i    , j - 1)
                  + c[ 8] * in(i + 1, j - 1)
                  + c[ 9] * in(i + 2, j - 1)
                  + c[10] * in(i - 2, j    )
                  + c[11] * in(i - 1, j    )
                  + c[12] * in(i    , j    )
                  + c[13] * in(i + 1, j    )
                  + c[14] * in(i + 2, j    )
                  + c[15] * in(i - 2, j + 1)
                  + c[16] * in(i - 1, j + 1)
                  + c[17] * in(i    , j + 1)
                  + c[18] * in(i + 1, j + 1)
                  + c[19] * in(i + 2, j + 1)
                  + c[20] * in(i - 2, j + 2)
                  + c[21] * in(i - 1, j + 2)
                  + c[22] * in(i    , j + 2)
                  + c[23] * in(i + 1, j + 2)
                  + c[24] * in(i + 2, j + 2);
