out(i    , j    , k    ) = c[ 0] * in(i    , j    , k    )
                         + c[ 1] * in(i - 8, j    , k    )
                         + c[ 2] * in(i - 7, j    , k    )
                         + c[ 3] * in(i - 6, j    , k    )
                         + c[ 4] * in(i - 5, j    , k    )
                         + c[ 5] * in(i - 4, j    , k    )
                         + c[ 6] * in(i - 3, j    , k    )
                         + c[ 7] * in(i - 2, j    , k    )
                         + c[ 8] * in(i - 1, j    , k    )
                         + c[ 9] * in(i + 1, j    , k    )
                         + c[10] * in(i + 2, j    , k    )
                         + c[11] * in(i + 3, j    , k    )
                         + c[12] * in(i + 4, j    , k    )
                         + c[13] * in(i + 5, j    , k    )
                         + c[14] * in(i + 6, j    , k    )
                         + c[15] * in(i + 7, j    , k    )
                         + c[16] * in(i + 8, j    , k    )
                         + c[17] * in(i    , j - 8, k    )
                         + c[18] * in(i    , j - 7, k    )
                         + c[19] * in(i    , j - 6, k    )
                         + c[20] * in(i    , j - 5, k    )
                         + c[21] * in(i    , j - 4, k    )
                         + c[22] * in(i    , j - 3, k    )
                         + c[23] * in(i    , j - 2, k    )
                         + c[24] * in(i    , j - 1, k    )
                         + c[25] * in(i    , j + 1, k    )
                         + c[26] * in(i    , j + 2, k    )
                         + c[27] * in(i    , j + 3, k    )
                         + c[28] * in(i    , j + 4, k    )
                         + c[29] * in(i    , j + 5, k    )
                         + c[30] * in(i    , j + 6, k    )
                         + c[31] * in(i    , j + 7, k    )
                         + c[32] * in(i    , j + 8, k    )
                         + c[33] * in(i    , j    , k - 8)
                         + c[34] * in(i    , j    , k - 7)
                         + c[35] * in(i    , j    , k - 6)
                         + c[36] * in(i    , j    , k - 5)
                         + c[37] * in(i    , j    , k - 4)
                         + c[38] * in(i    , j    , k - 3)
                         + c[39] * in(i    , j    , k - 2)
                         + c[40] * in(i    , j    , k - 1)
                         + c[41] * in(i    , j    , k + 1)
                         + c[42] * in(i    , j    , k + 2)
                         + c[43] * in(i    , j    , k + 3)
                         + c[44] * in(i    , j    , k + 4)
                         + c[45] * in(i    , j    , k + 5)
                         + c[46] * in(i    , j    , k + 6)
                         + c[47] * in(i    , j    , k + 7)
                         + c[48] * in(i    , j    , k + 8);
