out(i    , j    , k    ) = c[ 0] * in(i - 1, j - 1, k - 1)
                         + c[ 1] * in(i    , j - 1, k - 1)
                         + c[ 2] * in(i + 1, j - 1, k - 1)
                         + c[ 3] * in(i - 1, j    , k - 1)
                         + c[ 4] * in(i    , j    , k - 1)
                         + c[ 5] * in(i + 1, j    , k - 1)
                         + c[ 6] * in(i - 1, j + 1, k - 1)
                         + c[ 7] * in(i    , j + 1, k - 1)
                         + c[ 8] * in(i + 1, j + 1, k - 1)
                         + c[ 9] * in(i - 1, j - 1, k    )
                         + c[10] * in(i    , j - 1, k    )
                         + c[11] * in(i + 1, j - 1, k    )
                         + c[12] * in(i - 1, j    , k    )
                         + c[13] * in(i    , j    , k    )
                         + c[14] * in(i + 1, j    , k    )
                         + c[15] * in(i - 1, j + 1, k    )
                         + c[16] * in(i    , j + 1, k    )
                         + c[17] * in(i + 1, j + 1, k    )
                         + c[18] * in(i - 1, j - 1, k + 1)
                         + c[19] * in(i    , j - 1, k + 1)
                         + c[20] * in(i + 1, j - 1, k + 1)
                         + c[21] * in(i - 1, j    , k + 1)
                         + c[22] * in(i    , j    , k + 1)
                         + c[23] * in(i + 1, j    , k + 1)
                         + c[24] * in(i - 1, j + 1, k + 1)
                         + c[25] * in(i    , j + 1, k + 1)
                         + c[26] * in(i + 1, j + 1, k + 1);
